### ISSUE TITLE
Release Checklist

### ISSUE THREAD

**Issue by timplication** [oSoc19/opt-horison#59]
- [x] Make colors in the UI conform to Margot's styleguide. (Tinaël, Tim) [#57]
- [x] Redraw the isochrones upon dragging. (Bert, Tinaël) [#8]
- [x] Isochrone visualisation per user (Tim)
- [x] Deployment (Tim) [#7]
- [x] Make a demo gif for the presentation (All)
- [x] Updated Readme + GitHub Pages (?)

**Comment by HunteRoi** [comment]
Issue #66 spotted on user testing tonight. @BertSchoovaerts can you look into it whenever you have time? Would be great for it be solved before Monday
